spring:
  application:
    name: smartbill-backend
  
  datasource:
    url: jdbc:sqlserver://192.168.100.204:1433;databaseName=office;encrypt=true;trustServerCertificate=true
    username: applicationuser
    password: ApplicationUser2580
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.smartbill: DEBUG
    org.springframework.security: DEBUG
    org.springframework.jdbc: DEBUG

# TODO: 향후 환경변수로 관리 필요
app:
  jwt:
    secret: SmartBillSecretKeyForJWTTokenGenerationMustBe256BitsLongForHS256Algorithm
    expiration: 3600000  # 1시간 (레거시 쿠키와 동일)
